/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategoryCard: typeof import('./src/components/dashboard/category-card.vue')['default']
    ComponentCard: typeof import('./src/components/dashboard/component-card.vue')['default']
    DeleteDialog: typeof import('./src/components/shared/delete-dialog.vue')['default']
    DynamicDialog: typeof import('./src/components/shared/dynamic-dialog.vue')['default']
    DynamicToast: typeof import('./src/components/shared/dynamic-toast.vue')['default']
    MainLayout: typeof import('./src/components/layouts/main-layout.vue')['default']
    Pagination: typeof import('./src/components/shared/pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/shared/search-input.vue')['default']
    SkeletonTable: typeof import('./src/components/shared/skeleton-table.vue')['default']
  }
}
